# Tensors

Tensors are multi-dimensional array like data structures. But they can be run on GPU for faster operations/caculations.

In [1]:
import torch
import numpy as np

# Creating tensors

### From List

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_data

tensor([[1, 2],
        [3, 4]])

### From numpy arrays

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

x_np

tensor([[1, 2],
        [3, 4]])

### From another tensor

In [4]:
x_copy = torch.tensor(x_data)

# a tensor consisting of 1 with some dimension as another tensor
x_ones = torch.ones_like(x_data)

# a tensor consisting of random between 0 and 1 with some dimension as another tensor
# data type chenge is needed here because the surce could be of another data type
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(x_copy)
print(x_ones)
print(x_rand)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.4793, 0.6079],
        [0.3414, 0.1864]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


### With random or constant values based on shape

In [5]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
fives_tensor = 5*ones_tensor

print(rand_tensor)
print()
print(ones_tensor)
print()
print(zeros_tensor)
print()
print(fives_tensor)

tensor([[0.4668, 0.1195, 0.0722],
        [0.8048, 0.2564, 0.7900]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[5., 5., 5.],
        [5., 5., 5.]])


# Attributes of a tensor

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on tensors

### Moving a tensor to GPU

In [7]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

### Indexing and slicing

In [8]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])

print()
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concatenation

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Matrix Multiplication

In [10]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

### Element wise multiplication

In [11]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Single element tensor
If we have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()

In [12]:
agg = tensor.sum()
agg_item = agg.item()
print(agg, agg_item, type(agg_item))

tensor(12.) 12.0 <class 'float'>


### Inplace operations

In [13]:
print(tensor.add(5), "\n")
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Add an underscore '_' to the name of the operation to make it inplace

In [14]:
print(tensor.add_(5), "\n")
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
