# Preliminaries

## Basics

In [ ]:
import torch

In [ ]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel()

12

In [ ]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.randn(3, 4)

tensor([[ 0.0557,  0.7993,  0.2471, -0.0397],
        [-0.2987,  0.9348,  1.4043,  0.0209],
        [-1.6043, -1.4650,  2.0969,  0.9164]])

## Operations

### Element-wise

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])


In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = X*3
print(X)
print(Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  3.,  6.,  9.],
        [12., 15., 18., 21.],
        [24., 27., 30., 33.]])


In [ ]:
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  3.,  6.,  9.],
        [12., 15., 18., 21.],
        [24., 27., 30., 33.]])

In [ ]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  0.,  3.,  6.,  9.],
        [ 4.,  5.,  6.,  7., 12., 15., 18., 21.],
        [ 8.,  9., 10., 11., 24., 27., 30., 33.]])

In [ ]:
X==Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X.sum()

tensor(66.)

### Broadcasting

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Indexing and Slicing

In [ ]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [ ]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
print(X)
X[1, 2] = 9
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


In [ ]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Conversion to Other Python Objects

In [ ]:
A = X.numpy()
print(type(A))
print(A)

<class 'numpy.ndarray'>
[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]


In [ ]:
B = torch.from_numpy(A)
print(type(B))
print(B)

<class 'torch.Tensor'>
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [ ]:
a = torch.tensor([3.5])
a

tensor([3.5000])

In [ ]:
a.item()

3.5

In [ ]:
float(a)

3.5

In [ ]:
int(a)

3

## Exercises

<pre>
1. Run the code in this section. Change the conditional statement X == Y in this section 
to X < Y or X > Y, and then see what kind of tensor you can get.
2. Replace the two tensors that operate by element in the broadcasting mechanism with other
shapes, e.g., 3-dimensional tensors. Is the result the same as expected?
</pre>

In [ ]:
X<Y

tensor([[False, False, False, False],
        [False,  True,  True,  True],
        [ True,  True,  True,  True]])

In [ ]:
X>Y

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
print(X)
print(X.shape)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])
torch.Size([3, 4])


In [ ]:
X[1, 2] = torch.tensor([1, 2, 3])
print(X)
print(X.shape)

RuntimeError: ignored

In [ ]:
X[:] = torch.tensor([1, 2, 3])
print(X)
print(X.shape)

RuntimeError: ignored